server:
  port: 9002

  spring:
    application:
      name: USER-SERVICE

  eureka:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka/
      instance:
        hotname: localhost